"""empty message

Revision ID: 490b9354fd4b
Revises: 1b6a3ecb6143
Create Date: 2019-12-18 04:44:21.405506

"""

# revision identifiers, used by Alembic.
revision = '490b9354fd4b'
down_revision = '1b6a3ecb6143'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
